export const AUTH_ERROR_CODES = {
  INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  ACCOUNT_INACTIVE: 'AUTH_ACCOUNT_INACTIVE',
  ACCOUNT_SUSPENDED: 'AUTH_ACCOUNT_SUSPENDED',
  ACCOUNT_BLOCKED: 'AUTH_ACCOUNT_BLOCKED',
  ACCOUNT_LOCKED: 'AUTH_ACCOUNT_LOCKED',
  USERNAME_TAKEN: 'AUTH_USERNAME_TAKEN',
  PHONE_NUMBER_TAKEN: 'AUTH_PHONE_NUMBER_TAKEN',
  EMAIL_TAKEN: 'AUTH_EMAIL_TAKEN',
  SPONSOR_NOT_FOUND: 'AUTH_SPONSOR_NOT_FOUND',
  ACCESS_TOKEN_INVALID: 'AUTH_ACCESS_TOKEN_INVALID',
  ACCESS_TOKEN_EXPIRED: 'AUTH_ACCESS_TOKEN_EXPIRED',
  REFRESH_TOKEN_INVALID: 'AUTH_REFRESH_TOKEN_INVALID',
  REFRESH_TOKEN_EXPIRED: 'AUTH_REFRESH_TOKEN_EXPIRED',
  REFRESH_TOKEN_REVOKED: 'AUTH_REFRESH_TOKEN_REVOKED',
  RESET_TOKEN_INVALID: 'AUTH_RESET_TOKEN_INVALID',
  RESET_TOKEN_EXPIRED: 'AUTH_RESET_TOKEN_EXPIRED',
  CURRENT_PASSWORD_INCORRECT: 'AUTH_CURRENT_PASSWORD_INCORRECT',
  UNAUTHORIZED: 'AUTH_UNAUTHORIZED',
  FORBIDDEN: 'AUTH_FORBIDDEN',
} as const;

export type AuthErrorCode = (typeof AUTH_ERROR_CODES)[keyof typeof AUTH_ERROR_CODES];
