export { AppError, type ErrorDetail } from './app-error';
export { ValidationError } from './validation-error';
export { AuthenticationError } from './authentication-error';
export { AuthorizationError } from './authorization-error';
export { NotFoundError } from './not-found-error';
export { BusinessRuleError } from './business-rule-error';
export { WalletNotFoundError } from './wallet-not-found-error';
export { WalletNotActiveError } from './wallet-not-active-error';
export { InsufficientBalanceError } from './insufficient-balance-error';
export { DepositNotFoundError } from './deposit-not-found-error';
export { DepositNotPendingError } from './deposit-not-pending-error';
